name: imagecube

channels:
    - astropy

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - montage-wrapper
    # - pip:
      # - requirements.txt
